name: Deploy to Railway on Monday

on:
  schedule:
    - cron: '0 7 * * 1' # Tous les lundis à 07:00 UTC (09:00 heure de Paris)
  workflow_dispatch: # Permet aussi de le déclencher manuellement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway deploy
        run: |
          curl -X POST "https://backboard.railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}/deploy" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}"
